---
- hosts: web
  tasks:
    - name: installing apache 2
      apt:
        name: apache2
        state: present
    - name: check apache runnung status
      service:
        name: apache2
        state: started

